set(_CATKIN_CURRENT_PACKAGE "joint_state_reader")
set(joint_state_reader_VERSION "0.0.0")
set(joint_state_reader_MAINTAINER "team4 <team4@todo.todo>")
set(joint_state_reader_PACKAGE_FORMAT "2")
set(joint_state_reader_BUILD_DEPENDS "roscpp" "rospy" "sensor_msgs")
set(joint_state_reader_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "sensor_msgs")
set(joint_state_reader_BUILDTOOL_DEPENDS "catkin")
set(joint_state_reader_BUILDTOOL_EXPORT_DEPENDS )
set(joint_state_reader_EXEC_DEPENDS "roscpp" "rospy" "sensor_msgs")
set(joint_state_reader_RUN_DEPENDS "roscpp" "rospy" "sensor_msgs")
set(joint_state_reader_TEST_DEPENDS )
set(joint_state_reader_DOC_DEPENDS )
set(joint_state_reader_DEPRECATED "")