set(_CATKIN_CURRENT_PACKAGE "map_annotator")
set(map_annotator_VERSION "0.0.0")
set(map_annotator_MAINTAINER "team4 <team4@todo.todo>")
set(map_annotator_PACKAGE_FORMAT "2")
set(map_annotator_BUILD_DEPENDS "roscpp" "rospy" "message_generation")
set(map_annotator_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "message_runtime")
set(map_annotator_BUILDTOOL_DEPENDS "catkin")
set(map_annotator_BUILDTOOL_EXPORT_DEPENDS )
set(map_annotator_EXEC_DEPENDS "roscpp" "rospy" "message_runtime")
set(map_annotator_RUN_DEPENDS "roscpp" "rospy" "message_runtime")
set(map_annotator_TEST_DEPENDS )
set(map_annotator_DOC_DEPENDS )
set(map_annotator_DEPRECATED "")