set(_CATKIN_CURRENT_PACKAGE "fetch_ikfast_plugin")
set(fetch_ikfast_plugin_VERSION "0.7.14")
set(fetch_ikfast_plugin_MAINTAINER "Russell Toris <rtoris@fetchrobotics.com>, Alex Moriarty <amoriarty@fetchrobotics.com>")
set(fetch_ikfast_plugin_PACKAGE_FORMAT "2")
set(fetch_ikfast_plugin_BUILD_DEPENDS "liblapack-dev" "moveit_core" "pluginlib" "roscpp" "tf_conversions")
set(fetch_ikfast_plugin_BUILD_EXPORT_DEPENDS "liblapack-dev" "moveit_core" "pluginlib" "roscpp" "tf_conversions")
set(fetch_ikfast_plugin_BUILDTOOL_DEPENDS "catkin")
set(fetch_ikfast_plugin_BUILDTOOL_EXPORT_DEPENDS )
set(fetch_ikfast_plugin_EXEC_DEPENDS "liblapack-dev" "moveit_core" "pluginlib" "roscpp" "tf_conversions")
set(fetch_ikfast_plugin_RUN_DEPENDS "liblapack-dev" "moveit_core" "pluginlib" "roscpp" "tf_conversions")
set(fetch_ikfast_plugin_TEST_DEPENDS )
set(fetch_ikfast_plugin_DOC_DEPENDS )
set(fetch_ikfast_plugin_DEPRECATED "")