set(_CATKIN_CURRENT_PACKAGE "gizmo_description")
set(gizmo_description_VERSION "14.3.1")
set(gizmo_description_MAINTAINER "Kaijen Hsiao <kaijen@mayfieldrobotics.com>")
set(gizmo_description_PACKAGE_FORMAT "1")
set(gizmo_description_BUILD_DEPENDS )
set(gizmo_description_BUILD_EXPORT_DEPENDS "xacro")
set(gizmo_description_BUILDTOOL_DEPENDS "catkin")
set(gizmo_description_BUILDTOOL_EXPORT_DEPENDS )
set(gizmo_description_EXEC_DEPENDS "xacro")
set(gizmo_description_RUN_DEPENDS "xacro")
set(gizmo_description_TEST_DEPENDS "roslib")
set(gizmo_description_DOC_DEPENDS )
set(gizmo_description_DEPRECATED "")