set(_CATKIN_CURRENT_PACKAGE "collada_web_server")
set(collada_web_server_VERSION "0.0.0")
set(collada_web_server_MAINTAINER "jstn <jstn@todo.todo>")
set(collada_web_server_PACKAGE_FORMAT "2")
set(collada_web_server_BUILD_DEPENDS )
set(collada_web_server_BUILD_EXPORT_DEPENDS )
set(collada_web_server_BUILDTOOL_DEPENDS "catkin")
set(collada_web_server_BUILDTOOL_EXPORT_DEPENDS )
set(collada_web_server_EXEC_DEPENDS )
set(collada_web_server_RUN_DEPENDS )
set(collada_web_server_TEST_DEPENDS )
set(collada_web_server_DOC_DEPENDS )
set(collada_web_server_DEPRECATED "")