set(_CATKIN_CURRENT_PACKAGE "applications")
set(applications_VERSION "0.1.0")
set(applications_MAINTAINER "jstn <jstn@todo.todo>")
set(applications_PACKAGE_FORMAT "2")
set(applications_BUILD_DEPENDS "roscpp" "rospy" "joint_state_reader")
set(applications_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "joint_state_reader")
set(applications_BUILDTOOL_DEPENDS "catkin")
set(applications_BUILDTOOL_EXPORT_DEPENDS )
set(applications_EXEC_DEPENDS "roscpp" "rospy" "joint_state_reader")
set(applications_RUN_DEPENDS "roscpp" "rospy" "joint_state_reader")
set(applications_TEST_DEPENDS )
set(applications_DOC_DEPENDS )
set(applications_DEPRECATED "")