set(_CATKIN_CURRENT_PACKAGE "perception_msgs")
set(perception_msgs_VERSION "0.0.0")
set(perception_msgs_MAINTAINER "team4 <team4@todo.todo>")
set(perception_msgs_PACKAGE_FORMAT "2")
set(perception_msgs_BUILD_DEPENDS "geometry_msgs" "message_generation" "message_runtime")
set(perception_msgs_BUILD_EXPORT_DEPENDS "message_generation" "message_runtime")
set(perception_msgs_BUILDTOOL_DEPENDS "catkin")
set(perception_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(perception_msgs_EXEC_DEPENDS "message_generation" "message_runtime")
set(perception_msgs_RUN_DEPENDS "message_generation" "message_runtime")
set(perception_msgs_TEST_DEPENDS )
set(perception_msgs_DOC_DEPENDS )
set(perception_msgs_DEPRECATED "")