set(_CATKIN_CURRENT_PACKAGE "web_teleop")
set(web_teleop_VERSION "0.0.0")
set(web_teleop_MAINTAINER "wxyelaine <wxyelaine@todo.todo>")
set(web_teleop_PACKAGE_FORMAT "2")
set(web_teleop_BUILD_DEPENDS "joint_state_reader" "robot_api" "roscpp" "rospy" "message_generation")
set(web_teleop_BUILD_EXPORT_DEPENDS "joint_state_reader" "robot_api" "roscpp" "rospy" "message_runtime")
set(web_teleop_BUILDTOOL_DEPENDS "catkin")
set(web_teleop_BUILDTOOL_EXPORT_DEPENDS )
set(web_teleop_EXEC_DEPENDS "joint_state_reader" "robot_api" "roscpp" "rospy" "message_runtime")
set(web_teleop_RUN_DEPENDS "joint_state_reader" "robot_api" "roscpp" "rospy" "message_runtime")
set(web_teleop_TEST_DEPENDS )
set(web_teleop_DOC_DEPENDS )
set(web_teleop_DEPRECATED "")