set(_CATKIN_CURRENT_PACKAGE "robot_api")
set(robot_api_VERSION "0.1.0")
set(robot_api_MAINTAINER "Justin Huang <jstn@cs.washington.edu>")
set(robot_api_PACKAGE_FORMAT "2")
set(robot_api_BUILD_DEPENDS "actionlib" "control_msgs" "roscpp" "rospy" "trajectory_msgs")
set(robot_api_BUILD_EXPORT_DEPENDS "actionlib" "control_msgs" "roscpp" "rospy" "trajectory_msgs")
set(robot_api_BUILDTOOL_DEPENDS "catkin")
set(robot_api_BUILDTOOL_EXPORT_DEPENDS )
set(robot_api_EXEC_DEPENDS "actionlib" "control_msgs" "roscpp" "rospy" "trajectory_msgs")
set(robot_api_RUN_DEPENDS "actionlib" "control_msgs" "roscpp" "rospy" "trajectory_msgs")
set(robot_api_TEST_DEPENDS )
set(robot_api_DOC_DEPENDS )
set(robot_api_DEPRECATED "")