set(robot_api_SETUP_PY_VERSION "0.1.0")
set(robot_api_SETUP_PY_SCRIPTS "")
set(robot_api_SETUP_PY_PACKAGES "robot_api")
set(robot_api_SETUP_PY_PACKAGE_DIRS "src/robot_api")
set(robot_api_SETUP_PY_MODULES "")
set(robot_api_SETUP_PY_MODULE_DIRS "")